### ISSUE TITLE
Tabela uslugi

### ISSUE THREAD

**Issue by Kosek7** [Chr1skyy/Egzamin-Zawodowy-E14-EE09-INF03#2]
Uprawnienia mają być przyznane tylko do tabeli uslugi w bazie danych egzamin1, a nie do wszystkich tabel.

**Comment by Kosek7** [comment]
ścieżka do miejsca, gdzie jest błąd: ee09/ee09_2020_06_04/rozwiazanie/kw4.png

**Comment by Kosek7** [comment]
(oraz plik kwerendy.txt)

**Comment by Chr1skyy** [comment]
Dzięki za zwrócenie uwagi, już poprawiłem.
