### ISSUE TITLE
Błędy w egzaminie: e14_2019_06_02

### ISSUE THREAD

**Issue by Kosek7** [Chr1skyy/Egzamin-Zawodowy-E14-EE09-INF03#3]
Ścieżka (e14/e14_2019_06_02)
1. Wynik ze Skryptu 2 zaokrąglany jest do 2 miejsc po przecinku, zamiast do 1 (w rezultacie i tak to nic nie zmienia, bo żadna cena nie ma 2 miejsc po przecinku, ale still mógłby ci ktoś za to nie dać punkta - wymagane jest tylko 1 miejsce po przecinku)

2. Najeżdżając kursorem na dany wiersz tabeli, podświetla się tylko tekst komórki (kolor czcionki powinien się zmieniać dla całego wiersza)

Podsumowując błędy są w plikach: styl.css (48 wiersz, td -> tr), index.php (53 wiersz, po przecinku wpisz 1 zamiast 2).

PS. Dzięki, że dajesz mi możliwość powtórzenia przed egzaminem ;)

**Comment by Chr1skyy** [comment]
Dzięki za uważne sprawdzanie moich rozwiązań.

1. W arkuszu nic nie jest napisane o ilości miejsc po przecinku, dlatego zaokrągliłem tak jak powinny być zaokrąglane ceny.
2. Rzeczywiście, już poprawiam.
